import React from 'react';
import type { DesignProps, ExamViewModel } from './types';
import { getSyncStatus } from '../utils/syncStatus';
import FitText from '../components/FitText';
import './LightDesigns.css';

type Variant = 'sunrise' | 'palette' | 'orbit' | 'peach' | 'poster' | 'ice';

const Controls = ({ onBack, onOpenAnnouncements, onSwitchDesign, onAdmin }: Pick<DesignProps, 'onBack'|'onOpenAnnouncements'|'onSwitchDesign'|'onAdmin'>) => <div className="ld-actions"><button onClick={onBack} aria-label="返回">←</button><button onClick={onOpenAnnouncements} aria-label="公告">📢</button><button onClick={onSwitchDesign} aria-label="切换设计">▣</button><button onClick={onAdmin} aria-label="管理">⚙</button></div>;
function title(vm: ExamViewModel) { return vm.phase === 'empty' ? '暂未配置考试安排' : vm.phase === 'before' ? (vm.currentName ? `距 ${vm.currentName} 开考` : '下一科待定') : vm.phase === 'ended' ? (vm.currentName ? `${vm.currentName} 已结束` : '今日考试已全部结束') : (vm.currentName ?? '考试进行中'); }
function pct(vm: ExamViewModel) { return vm.phase === 'ended' ? 100 : vm.phase === 'live' ? Math.max(0, Math.min(100, vm.progressPct)) : 0; }
function next(vm: ExamViewModel) { return vm.nextName ? `${vm.nextName}${vm.nextStartHM ? ` · ${vm.nextStartHM}` : ''}` : '暂无下一科'; }
function remain(vm: ExamViewModel) { return vm.phase === 'live' ? vm.remainingText : vm.countdownText; }
function Data({ vm }: {vm: ExamViewModel}) { const p=pct(vm); return <><div className="ld-progress"><i style={{width:`${p}%`}}/></div><div className="ld-meta"><span>{vm.phase === 'before' ? '距开考' : '已进行'} <b>{vm.phase === 'before' ? vm.countdownText : vm.elapsedText}</b></span><span className={vm.urgency === 'normal' ? '' : 'warn'}>{vm.phase === 'live' ? `剩余 ${vm.remainingText}` : `${Math.round(p)}%`}</span></div></>; }
function LightDesign({ variant, ...props }: DesignProps & {variant: Variant}) { const {vm,onDismissNotification}=props; const p=pct(vm); const sync=getSyncStatus(vm.online,vm.timeSynced); const ring=2*Math.PI*118; const date=vm.dateText.split('·');
 return <div className={`ld ld-${variant}`}>
  {variant==='sunrise' && <i className="ld-sun" aria-hidden="true"/>}
  <header className="ld-head"><div><span className="ld-brand">{variant==='palette'?'EXAM CONTROL':variant==='orbit'?'2026 · EXAM BOARD':vm.masterTitle || '考试看板'}</span>{variant==='peach'&&<small>{vm.dateText}</small>}</div><div><span className={`ld-sync is-${sync.tone}`}>{sync.text}</span><Controls {...props}/></div></header>
  {vm.notification && <div className="ld-notice"><span>{vm.notification.icon}</span><span>{vm.notification.message}</span><button onClick={onDismissNotification} aria-label="关闭">×</button></div>}
  {variant==='orbit' ? <main className="ld-orbit-main"><h1>{title(vm)}</h1><FitText className="ld-clock">{vm.clock}</FitText><p>{vm.dateText}</p><section className="ld-orbit-row"><div><span>已进行</span><b>{vm.elapsedText}</b></div><div className="ld-ring"><svg viewBox="0 0 280 280"><circle cx="140" cy="140" r="118"/><circle className="ld-ring-value" cx="140" cy="140" r="118" style={{strokeDasharray:ring,strokeDashoffset:ring*(1-p/100)}}/></svg><strong>{Math.round(p)}%<small>当前进度</small></strong></div><div><span>下一科</span><b>{next(vm)}</b></div></section></main> : variant==='peach' ? <main className="ld-peach-main"><aside><span>EXAM</span><b>{new Date().getFullYear()}</b><strong>{vm.clock.slice(0,2)}<br/>{vm.clock.slice(3,5)}</strong></aside><section><p className="ld-tag">{vm.phase==='live'?'当前考试':'考试安排'}</p><h1>{title(vm)}</h1><p>{vm.startHM&&vm.endHM?`${vm.startHM} — ${vm.endHM}`:vm.dateText}</p><div className="ld-peach-progress"><Data vm={vm}/></div><div className="ld-queue"><div><span>当前</span><b>{vm.currentName ?? '暂未配置考试'}</b><em>{vm.startHM ?? '—'}</em></div>{vm.nextName&&<div><span>下一科</span><b>{vm.nextName}</b><em>{vm.nextStartHM}</em></div>}</div></section></main> : variant==='ice' ? <main className="ld-ice-main"><aside><span>EXAM</span><p>{date[date.length-1]?.trim()}</p><strong>{vm.clock.slice(0,2)}<br/>{vm.clock.slice(3,5)}</strong><b>{date[1]?.trim() ?? '北京时间'}</b></aside><section><h1>{title(vm)}</h1><FitText className="ld-clock">{vm.clock}</FitText><p>{vm.dateText}</p><Data vm={vm}/></section><aside><span>{vm.phase==='before'?'距开考':'剩余时间'}</span><strong>{remain(vm)}</strong><hr/><span>下一科</span><b>{next(vm)}</b></aside></main> : <main className="ld-standard"><section className="ld-primary"><p className="ld-tag">{variant==='poster'?'EXAM TIME':variant==='sunrise'?'考试进行中':'当前考试'}</p><h1>{title(vm)}</h1>{vm.startHM&&vm.endHM&&<p>{vm.startHM} — {vm.endHM}</p>}<FitText className="ld-clock"><b>{variant==='sunrise'||variant==='poster'?vm.clock.slice(0,5):vm.clock}</b>{(variant==='sunrise'||variant==='poster')&&<em>{vm.clock.slice(5)}</em>}</FitText><p>{vm.dateText}</p><Data vm={vm}/></section>{variant==='poster'?<section className="ld-poster-side"><b>{Math.round(p)}%</b><span>当前进度</span><div><span>剩余时间</span><b>{remain(vm)}</b></div><div><span>下一科</span><b>{next(vm)}</b></div></section>:<section className="ld-cards"><div><span>当前进度</span><b>{Math.round(p)}%</b></div><div><span>{vm.phase==='before'?'距开考':'剩余时间'}</span><b>{remain(vm)}</b></div><div><span>下一科</span><b>{next(vm)}</b></div><div><span>当前状态</span><b>{vm.phase==='live'?'进行中':vm.phase==='before'?'候考中':vm.phase==='ended'?'已结束':'待配置'}</b></div></section>}</main>}
 </div>;
}
export const SunriseSchedule=(p:DesignProps)=><LightDesign variant="sunrise" {...p}/>;
export const PaletteDashboard=(p:DesignProps)=><LightDesign variant="palette" {...p}/>;
export const OrbitFocus=(p:DesignProps)=><LightDesign variant="orbit" {...p}/>;
export const PeachTaskBoard=(p:DesignProps)=><LightDesign variant="peach" {...p}/>;
export const PosterGrid=(p:DesignProps)=><LightDesign variant="poster" {...p}/>;
export const IceColumns=(p:DesignProps)=><LightDesign variant="ice" {...p}/>;
